In [84]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [85]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split

df = pd.read_csv('/Users/namin/Desktop/ÎåÄÌïô/3ÌïôÎÖÑ 1ÌïôÍ∏∞/Ïù∏Í≥µÏßÄÎä•Í∞úÎ°†/AI-Class/AI-Class/week03/abalone.csv', index_col=0)
df

,Sex,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Rings
id,,,,,,,,,
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

In [86]:
# Í∏∞Ï¥à ÌÜµÍ≥ÑÎüâ ÌôïÏù∏
print("\nüìå Îç∞Ïù¥ÌÑ∞ Í∏∞Ï¥à ÌÜµÍ≥ÑÎüâ:")
print(df.describe())

# Í≤∞Ï∏°Ïπò ÌôïÏù∏
print("\nüìå Ïª¨ÎüºÎ≥Ñ Í≤∞Ï∏°Ïπò Í∞úÏàò:")
print(df.isnull().sum())

üìå Îç∞Ïù¥ÌÑ∞ Í∏∞Ï¥à ÌÜµÍ≥ÑÎüâ:
            Length     Diameter       Height  Whole_weight  Shucked_weight  \
count  4177.000000  4177.000000  4177.000000   4177.000000     4177.000000
mean      0.523992     0.407881     0.139516      0.828742        0.359367
std       0.120093     0.099240     0.041827      0.490389        0.221963
min       0.075000     0.055000     0.000000      0.002000        0.001000
25%       0.450000     0.350000     0.115000      0.441500        0.186000
50%       0.545000     0.425000     0.140000      0.799500        0.336000
75%       0.615000     0.480000     0.165000      1.153000        0.502000
max       0.815000     0.650000     1.130000      2.825500        1.488000

       Viscera_weight  Shell_weight        Rings
count     4177.000000   4177.000000  4177.000000
mean         0.180594      0.238831     9.933684
std          0.109614      0.139203     3.224169
min          0.000500      0.001500     1.000000
25%          0.093500      0.130000     8.000000
50%          0.171000      0.234000     9.000000
75%          0.253000      0.329000    11.000000
max          0.760000      1.005000    29.000000

üìå Ïª¨ÎüºÎ≥Ñ Í≤∞Ï∏°Ïπò Í∞úÏàò:
Sex               0
Length            0
Diameter          0
Height            0
Whole_weight      0
Shucked_weight    0
Viscera_weight    0
Shell_weight      0
Rings             0
dtype: int64

In [87]:
# Î™©Ìëú Î≥ÄÏàò ÏÑ§Ï†ï
X = df.drop('Rings', axis=1)  # 'Rings'Î•º Ï†úÏô∏Ìïú ÎÇòÎ®∏ÏßÄÍ∞Ä ÏûÖÎ†• Îç∞Ïù¥ÌÑ∞
y = df['Rings']# ÏòàÏ∏°Ìï† Î™©Ìëú Î≥ÄÏàò

X.head()

,Sex,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight
id,,,,,,,,
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055

In [88]:
y = df['Rings']
y.head()

id
0    15
1     7
2     9
3    10
4     7
Name: Rings, dtype: int64

In [89]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test=train_test_split(X,
                                                  y,
                                                  test_size=0.2,
                                                  shuffle=True,
                                                  random_state=12)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(3341, 8) (3341,)
(836, 8) (836,)

In [96]:
# ID Ïª¨Îüº Ï†úÍ±∞ (ÌïÑÏöîÌïú Í≤ΩÏö∞)
df = df.drop(columns=['id'], errors='ignore')

print(df.head())

   Sex  Length  Diameter  Height  Whole_weight  Shucked_weight  \
id
0    M   0.455     0.365   0.095        0.5140          0.2245
1    M   0.350     0.265   0.090        0.2255          0.0995
2    F   0.530     0.420   0.135        0.6770          0.2565
3    M   0.440     0.365   0.125        0.5160          0.2155
4    I   0.330     0.255   0.080        0.2050          0.0895

    Viscera_weight  Shell_weight  Rings
id
0           0.1010         0.150     15
1           0.0485         0.070      7
2           0.1415         0.210      9
3           0.1140         0.155     10
4           0.0395         0.055      7

In [100]:
# 'sex' Ïª¨ÎüºÏùÑ Ïõê-Ìï´ Ïù∏ÏΩîÎî©
df = pd.get_dummies(df, columns=['Sex'], drop_first=True)

print(df.head())

    Length  Diameter  Height  Whole_weight  Shucked_weight  Viscera_weight  \
id
0    0.455     0.365   0.095        0.5140          0.2245          0.1010
1    0.350     0.265   0.090        0.2255          0.0995          0.0485
2    0.530     0.420   0.135        0.6770          0.2565          0.1415
3    0.440     0.365   0.125        0.5160          0.2155          0.1140
4    0.330     0.255   0.080        0.2050          0.0895          0.0395

    Shell_weight  Rings  Sex_I  Sex_M
id
0          0.150     15  False   True
1          0.070      7  False   True
2          0.210      9  False  False
3          0.155     10  False   True
4          0.055      7   True  False

In [102]:
# X (ÏûÖÎ†• Îç∞Ïù¥ÌÑ∞), y (ÏòàÏ∏°Ìï† ÌÉÄÍ≤üÍ∞í) ÏÑ§Ï†ï
X = df.drop(columns=['Rings'])  # ÌÉÄÍ≤ü Ïª¨Îüº Ï†úÍ±∞
y = df['Rings']  # ÏòàÏ∏°Ìï† Í∞í

print("\nüìå X Îç∞Ïù¥ÌÑ∞ ÏÉòÌîå:")
print(X.head())

print("\nüìå y Îç∞Ïù¥ÌÑ∞ ÏÉòÌîå:")
print(y.head())

üìå X Îç∞Ïù¥ÌÑ∞ ÏÉòÌîå:
    Length  Diameter  Height  Whole_weight  Shucked_weight  Viscera_weight  \
id
0    0.455     0.365   0.095        0.5140          0.2245          0.1010
1    0.350     0.265   0.090        0.2255          0.0995          0.0485
2    0.530     0.420   0.135        0.6770          0.2565          0.1415
3    0.440     0.365   0.125        0.5160          0.2155          0.1140
4    0.330     0.255   0.080        0.2050          0.0895          0.0395

    Shell_weight  Sex_I  Sex_M
id
0          0.150  False   True
1          0.070  False   True
2          0.210  False  False
3          0.155  False   True
4          0.055   True  False

üìå y Îç∞Ïù¥ÌÑ∞ ÏÉòÌîå:
id
0    15
1     7
2     9
3    10
4     7
Name: Rings, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

# Îç∞Ïù¥ÌÑ∞ Î∂ÑÌï†
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=12)

print("\n‚úÖ Îç∞Ïù¥ÌÑ∞ Î∂ÑÌï† ÏôÑÎ£å!")
print("X_train:", X_train.shape, "y_train:", y_train.shape)
print("X_test:", X_test.shape, "y_test:", y_test.shape)