In [9]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from scipy import stats

In [11]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split

df = pd.read_csv('/Users/namin/Desktop/대학/3학년 1학기/인공지능개론/AI-Class/AI-Class/week04/wine.csv', index_col=0)
df

,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
Wine,,,,,,,,,,,,,
1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [13]:
# 기초 통계량 확인
print("\n 데이터 기초 통계량:")
print(df.describe())

# 결측치 확인
print("\n 컬럼별 결측치 개수:")
print(df.isnull().sum())

데이터 기초 통계량:
          Alcohol  Malic.acid         Ash         Acl          Mg     Phenols  \
count  178.000000  178.000000  178.000000  178.000000  178.000000  178.000000
mean    13.000618    2.336348    2.366517   19.494944   99.741573    2.295112
std      0.811827    1.117146    0.274344    3.339564   14.282484    0.625851
min     11.030000    0.740000    1.360000   10.600000   70.000000    0.980000
25%     12.362500    1.602500    2.210000   17.200000   88.000000    1.742500
50%     13.050000    1.865000    2.360000   19.500000   98.000000    2.355000
75%     13.677500    3.082500    2.557500   21.500000  107.000000    2.800000
max     14.830000    5.800000    3.230000   30.000000  162.000000    3.880000

       Flavanoids  Nonflavanoid.phenols     Proanth   Color.int         Hue  \
count  178.000000            178.000000  178.000000  178.000000  178.000000
mean     2.029270              0.361854    1.590899    5.058090    0.957449
std      0.998859              0.124453    0.572359    2.318286    0.228572
min      0.340000              0.130000    0.410000    1.280000    0.480000
25%      1.205000              0.270000    1.250000    3.220000    0.782500
50%      2.135000              0.340000    1.555000    4.690000    0.965000
75%      2.875000              0.437500    1.950000    6.200000    1.120000
max      5.080000              0.660000    3.580000   13.000000    1.710000

               OD      Proline
count  178.000000   178.000000
mean     2.611685   746.893258
std      0.709990   314.907474
min      1.270000   278.000000
25%      1.937500   500.500000
50%      2.780000   673.500000
75%      3.170000   985.000000
max      4.000000  1680.000000

컬럼별 결측치 개수:
Alcohol                 0
Malic.acid              0
Ash                     0
Acl                     0
Mg                      0
Phenols                 0
Flavanoids              0
Nonflavanoid.phenols    0
Proanth                 0
Color.int               0
Hue                     0
OD                      0
Proline                 0
dtype: int64